version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NAME=Develop César
      - PORT=3000
      - MONGO_USER=dbmongo
      - MONGO_PASSWORD=p4ssw0rd
      - SESSION_SECRET=secret
    command: npm run dev
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dbmongo
      - MONGO_INITDB_ROOT_PASSWORD=p4ssw0rd