version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_IP=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=dbmongo
      - MONGO_PASSWORD=p4ssw0rd
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dbmongo
      - MONGO_INITDB_ROOT_PASSWORD=p4ssw0rd
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: